liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    # filter_sets:
    #     my_thumb_jpeg: # Define your filter
    #         format: jpeg
    #         quality: 80
    #         filters:
    #             thumbnail: { size: [223, 223], mode: inset }
