sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

app_admin_custom_page:
    path: /admin/sipman/syncproduct
    methods: [GET, POST]
    defaults:
        _controller: App\Controller\Admin\SyncProductController::index

admin_run_command:
    path: /admin/runcommand
    methods: [GET]
    defaults:
        _controller: App\Controller\Admin\RunCommandController::index

admin_execute_command:
    path: /admin/executecommand/{commandName}
    methods: [GET]
    defaults:
        _controller: App\Controller\Admin\RunCommandController::executeCommand

admin_sipman_sync_wine:
    path: /admin/sipman/sync-wine
    methods: [GET]
    defaults:
        _controller: App\Controller\Admin\SyncProductController::sync

admin_sipman_update_taxons:
    path: /admin/sipman/update-taxon-product
    methods: [GET]
    defaults:
        _controller: App\Controller\Admin\SyncProductController::updateTaxons

admin_taxon_create:
    path: /admin/taxon/create
    methods: [GET]
    defaults:
        _controller: App\Controller\Admin\TaxonController::createTaxon

sylius_shop_product_show:
    path: /{_locale}/products/{slug}
    methods: [GET]
    defaults:
        _controller: App\Controller\ProductDetailController::showAction

