# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US
    csv_directory: '%kernel.project_dir%/public/uploads/csv'
    image_directory: '%kernel.project_dir%/public/media/image/wine'

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    app.listener.admin.menu_builder:
        class: App\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    App\Repository\CustomChannelRepository:
        autowire: true
        public: false

    # If you're directly using Sylius' repository interface
    Sylius\Component\Core\Repository\ChannelRepositoryInterface:
        alias: 'sylius.repository.channel'
    
    sylius.factory.channel_pricing:
        class: Sylius\Component\Resource\Factory\Factory
        arguments: ['%sylius.model.channel_pricing.class%']

    App\Controller\Admin\SyncProductController:
        arguments:
            $client: '@http_client'
            $connection: '@doctrine.dbal.default_connection'
            $productFactory: '@sylius.factory.product'
            $variantFactory: '@sylius.factory.product_variant'
            $productRepository: '@sylius.repository.product'
            $channelRepository: '@sylius.repository.channel'
            $entityManager: '@doctrine.orm.entity_manager'
            $channelPricingFactory: '@sylius.factory.channel_pricing'
    
    App\Command\SyncProductCommand:
        arguments:
            $imageDirectory: '%image_directory%'

    App\Service\WineService:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
